env:
  global:
    secure: "Q3w8wSrNwgfyG5rqm3VxVfelPfVivdzN8TCYsjecB6HRGFPcnG8Wb6XQyJXsvnf4KfosdrDVv7OLDMeF+UZqDa4hf/Sdm1vysInrBX16BVimRCbbQ/AsZYvcxw9mGHgyu6yB4Dy+3RhSmD7CwtoJDeMitBK/X29wU5I/sWFj0ciwvlACJ2gpDTeM7eqXdcygAIukPWdXFhE7SxRB7eN06+RTO7P2Uhbs/VIsXuoTElQk0kBM/s6YBoLKg9j31p/OAS8jX9cnp/eMHF105WSeN8lLSUEad3/dfSINCbTnSUjOPmcm7PtHCQmWE2qalKaxZsnhid7M6UvN976rcFh9kO753zh8fHihqrfRMU8PLMlY7e542JYyAMmZEzNqPwwooJj056eu2OHtyDqnU6AzF8f1dpTFhCvtguAXfvqBaHHIbDMa6Dxk5qXViXsE2P60dYJmE0vbYc0TDnNPvjabi6sc5KUx/rL+vdIBLu9/GLtTr/36Se5srik4JYcSypBH6MdLhP36jt9w4/jrKFSCSl6To1X1Lsf1hQIu0PpQ5VMz3mmK1vphjhjBeBaZZ1m82O4jNLb+z1A8aAx7/f978ooyQwCte0jg2kmz1PR72FIHXipXNsUePhBt3Ny6CR/PBIlwwFylOC78Pl7u7HR97twZ2qREv8ZuZr0l5LpLHDQ="

language: node_js
node_js: stable
sudo: false
after_success: npm run deploy
